CREATE DATABASE IF NOT EXISTS `robot_dashboard` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE `robot_dashboard`;

CREATE TABLE IF NOT EXISTS guild_settings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  guild_id VARCHAR(32) NOT NULL,
  prefix VARCHAR(8) NOT NULL DEFAULT '!',
  log_channel_id VARCHAR(32) DEFAULT NULL,
  language VARCHAR(8) NOT NULL DEFAULT 'pt-BR',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_guild (guild_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS audit_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  guild_id VARCHAR(32) NOT NULL,
  actor_id VARCHAR(32) DEFAULT NULL,
  action VARCHAR(64) NOT NULL,
  payload JSON DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_guild_created (guild_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
